for cmake3 make tbb an imported target
justusc/FindTBB pull request #6
Opened 2016-10-26 15:49 UTC by pwm1234

addresses an error when exporting a target that depends on tbb

I described this error with more detail in #5. I am by no means a cmake expert, but I needed this change for my work, and I wanted to contribute back since I have found findTBB.cmake helpful.

2016-10-26 15:55 UTC, justusc requested changes
Thanks for the pull request.

The initial changes look OK, but similar changes will also need to be applied to the other branches below.

Did you by any chance run the test project?

2016-10-26 16:00 UTC, pwm1234 commented
No, I did not run the test project. Let me do that and let you know how things go. I just ran into some weirdness that I need to investigate, so put this pull request on hold for now. (Is there a formal way to do that?) I will send you a note when I have tried the test and think it is ready.
Phil

From: Justus Calvin [mailto:notifications@github.com]
Sent: Wednesday, October 26, 2016 11:56 AM
To: justusc/FindTBB <FindTBB@noreply.github.com>
Cc: Philip Miller <philip.miller@sri.com>; Author <author@noreply.github.com>
Subject: Re: [justusc/FindTBB] for cmake3 make tbb an imported target (#6)


@justusc requested changes on this pull request.

Thanks for the pull request.

The initial changes look OK, but similar changes will also need to be applied to the other branches below.

Did you by any chance run the test project?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/justusc/FindTBB/pull/6#pullrequestreview-5888452>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ABcK4PMnvEaZZQ2-0IpulMdz-bUsItFaks5q33gGgaJpZM4KhV2E>.

2016-10-26 16:32 UTC, justusc commented
Exporting external targets into a config file is a non-trivial process. The documentation on the procedure is very sparse. The trick is that you have to recreate the external targets in your exported config file. The recommended procedure is: (1) export the find module into the same directory as your config file, and (2) write your config file to use the find module to recreate the external target (i.e. the TBB target). Another approach is to use the TBB _variables_ to set the appropriate compile options for your exported libraries. Unfortunately the second option precludes using the TBB target in your project as it will result in errors.

The test project is just the project I used to ensure that FindTBB is working as expected and can be used to build an executable. To run the test project run `cmake .` in the test directory.

Try modifying the test project to be a minimal example of what you are trying to do in your project.

I will look into this issue in more detail later this week, if you don't beat me to it.

2016-10-26 20:43 UTC, pwm1234 commented
Well, I gave it my best effort. The problem with my first attempt was I used INTERFACE_LINK_LIBRARIES for an imported target, which is not correct. I just pushed a commit to my pull request where I use ``IMPORTED_LOCATION_<CONFIG>``, which I think is the correct way to configure an imported target. I also added to the test project install export rules that demonstrate the original error that made me go down this path in the first place. 

I tried to put in changes for the other two branches (where (1) only TBB_LIBRARIES_RELEASE is defined, or (2) neither TBB_LIBRARIES_RELEASE nor TBB_LIBRARIES_DEBUG are defined), but that logic seems a little strange and testing it with msvc14, which always defines both, seems to take more time than I have right now.

I hope this PR is helpful.

2016-10-26 20:48 UTC, justusc commented
I think you are going in the right direction, but exporting targets in CMake is a tricky business. In my own projects, I just used the TBB variables directly to create executables and libraries in config files. I will try to get it working as soon as I have some free time. Hopefully this weekend.

2016-10-26 21:26 UTC, pwm1234 commented
I think the focus of this issue and the pull request is to change the tbb target from being an INTERFACE target to being an IMPORTED target. (This is what FindBoost.cmake does in cmake 3.6). 

Yes, I understand that exporting targets in CMake is tricky; I admit that I understand little about it, so I appreciate you taking time to look at this. Also, by no means do I think my pull request has a good example of exporting a target. It is just a demonstration of the error I encountered when exporting a target that used the tbb target.

2016-11-06 20:05 UTC, merged

2016-11-06 20:30 UTC, justusc commented
The changes you made in your PR were mostly correct. I made a minor change to the FindTBB.cmake file. Otherwise, everything looked good.

I also expanded the test to verify that the FindTBB script can be used by projects that export executables and shared libraries that depend on TBB.

2016-11-07 13:00 UTC, pwm1234 commented
Thank you! I appreciate you making FindTBB available and your time incorporating this request.